### PR TITLE
Add a link to promise-ring package to Convenience Utilities section.

### PR DESCRIPTION
**Pull request by DavidAnson**
Wrote this a few months back when I couldn't find quite what I was looking for. Per the overview:

> promise-ring is small, simple library with no dependencies that eases the use of native JavaScript Promises in projects without a Promise library.

https://github.com/DavidAnson/promise-ring

### CODE REVIEW

**Comment by wbinnssmith** [comment]
I'm really conflicted about including this, mostly because it's well-written and useful, but I'm not sure what it gives over something like @sindresorhus's [`pify`](https://github.com/sindresorhus/pify) and native Function `bind` and `apply`. `pify` also really just does the one thing well (although it does offer wrapAll as well) and returns functions that can be bound an called like any other.

I'm going to leave this open and see what other folks think, and I'd be glad to include it if others find it useful.

Great work :smile:

**Comment by DavidAnson** [comment]
Thanks a lot for your consideration! `pify` looks quite similar and I might have used it myself if it existed when I wrote `promise-ring`. :) `promise-ring` offers a few more methods to control exactly how a function is wrapped, but not the ability to pass a custom `Promise` implementation (probably the one thing I might add). I think we identified the same need and solved it slightly differently.

**Comment by sindresorhus** [comment]
I don't see the point of many of those methods. It feels like having methods just for the sake of it.

You can literally do everything with wrap:

```js
pr.call(fs.readFile, "../package.json", { "encoding": "utf8" });
pr.wrap(fs.readFile)("../package.json", { "encoding": "utf8" });
```

```js
pr.callBound(db, db.query, "promise-ring")
pr.wrap(db.query.bind(db))("promise-ring")
```

**Comment by DavidAnson** [comment]
You make great points. :)

At the time, I thought the API should be consistent with the native `call`/`apply` functions and modelled things that way. `call` was therefore only interesting for one-offs or single calls to a function. I chose to add `wrap` for scenarios where the target function was going to be invoked multiple times. As you point out, `wrap` can also be used for one-off invocations (at a seemingly tiny additional cost), but I was still of the mindset that a minimal/consistent API was the best approach. (This also seems to have the advantage that `pr.apply` works like `pr.call`, but maybe that's not significant.) I quite like the elegance of the model you've taken with `pify`.

Regarding the backwards compatibility issues around translating multiple parameters to an `Array`, that's a scenario I hadn't considered at all. :( The link you provided was enlightening and I regret the oversight.

I very much appreciate you taking the time to share your thoughts - thanks again!

**Pull request closed without merging**
